config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get '/home', to: "pages#home"
  get '/components', to: "pages#components"  #a retirer
  get '/rules', to: "pages#rules"
  get '/tutoriel', to: "pages#tutoriel"
  get '/reglages', to: "pages#reglages"
  get '/profil', to: "pages#profil"
  get 'pages/ending_adventure_show', to: 'pages#ending_adventure_show', as: 'ending_adventure_show'
  get 'pages/defeat', to: 'pages#defeat', as: 'defeat'

  get '/final_score', to: 'pages#final_score', as: 'final_score'
  get 'pages/notes', to: 'pages#notes', as: 'notes'

  get '/hint', to: "pages#hint"
  get '/user_games/:user_game_id/enigma/:enigma_id', to: "user_games#penalty", as: "penalty"

  post "/user_games/:id/victory", to: "user_games#victory", as: 'victory'

  resources :games do
    # resources :user_games, only: [:create]
    # resources :enigmas, only: [:show]
    resources :user_games, only: [:create]

  end

  resources :user_games, only: [:show, :update]
  resources :enigmas, only: [:show]

  resources :enigmas do
    get 'false_answer_popup', on: :member
      get 'hint_popup', on: :member
      get '/enigmas/bomb', to: 'enigmas#bomb', as: 'bomb'

  end





resources :point_of_interests, only:[:show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :enigma
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :users
end

app/models/enigma.rb
class Enigma < ApplicationRecord
  belongs_to :point_of_interest, optional: true
  has_many :answers
  has_one :hint
  belongs_to :game, class_name: 'Game'
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :user_games
  has_many :enigmas
end

app/models/hint.rb
class Hint < ApplicationRecord
  belongs_to :enigma
  has_many :user_games_hints
end

app/models/point_of_interest.rb
class PointOfInterest < ApplicationRecord
  has_many :enigmas

  def enigma
    enigmas.first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_games, dependent: :destroy
  # belongs_to :badge
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_game.rb
class UserGame < ApplicationRecord
  belongs_to :user
  belongs_to :game
  has_many :user_games_hints
end

app/models/user_game_hint.rb
class UserGameHint < ApplicationRecord
  belongs_to :hints
  belongs_to :user_games
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :set_enigma, only: [:index, :new, :create]

  def index
    @answers = @enigma.answers
  end

  def show
  end

  def new
    @answer = @enigma.answers.build
  end

  def create
    @answer = @enigma.answers.build(answer_params)

    if @answer.save
      redirect_to @answer, notice: 'Answer was successfully created.'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer, notice: 'Answer was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to answers_url, notice: 'Answer was successfully destroyed.'
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_enigma
    @enigma = Enigma.find(params[:enigma_id])
  end

  def answer_params
    params.require(:answer).permit(:enigma_id, :is_good_answer, :content, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(params[:id])
    @badge = current_user
  end
end

app/controllers/enigmas_controller.rb
class EnigmasController < ApplicationController
  before_action :set_enigma, only: [:show, :update, :destroy]

  def index
    @enigmas = Enigma.all
  end

  def show
    @answers = @enigma.answers
    @last_enigma = Enigma.last
    @user_game = UserGame.where(user: current_user).last

  end

  def new
    @enigma = Enigma.new
  end


  def create
    @enigma = Enigma.new(enigma_params)

    if @enigma.save
      redirect_to @enigma, notice: 'Enigma was successfully created.'
    else
      render :new
    end
  end

  def update
    if @enigma.update(enigma_params)
      redirect_to @enigma, notice: 'Enigma was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @enigma.destroy
    redirect_to enigmas_url, notice: 'Enigma was successfully destroyed.'
  end

  private

  #PAS CERTAIN, Permet de choisir l'énigme et ses POI, Hints associés en fonction.
  def set_enigma
    @enigma = Enigma.find(params[:id])
  end

  def enigma_params
    params.require(:enigma).permit(:title, :description, :image)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  skip_before_action :authenticate_user!, only: :show
  def show
    @game = Game.find(params[:id])
  end


end

app/controllers/hints_controller.rb
class HintsController < ApplicationController
  before_action :set_point_of_interest, only: [:show]

  def index
    @hints = Hint.all
  end

  def show
  end

  private

  def set_hint
    @hint = Hint.find(params[:id])
  end

  def hint_params
    params.require(:hint).permit(:content, :enigma_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 # skip_before_action :authenticate_user!, only: :home

  def home
    @games = Game.all
  end

  def components
  end

  def ending_adventure_show
  end

  def final_score
  end

  def notes

    @user_game = UserGame.where(user: current_user).last
  end

  # def bombe
  #   @user_game = UserGame.where(user: current_user).last
  # end

  def defeat
  end

  # def bombe_answer
  #   if params["code"] == "3492179918"
  #     redirect_to ending_adventure_show_path
  #   end
  # end

end

app/controllers/user_games_controller.rb
class UserGamesController < ApplicationController

  def index
    @user_game = current_user.users
  end


  def create
    @user_game = UserGame.new
    @user_game.user = current_user
    @user_game.game = Game.find(params[:game_id])
    @user_game.end_of_game_time = Time.now + @user_game.game.max_duration_in_sec
    @user_game.save
    redirect_to enigma_path(@user_game.game.enigmas.first)
  end

  def show
    @user_game = UserGame.find(params[:id])
    @enigmas = Enigma.where(game_id: @user_game.game.id)
  end

  def progression
    @progression = Enigma.all
    @start = @progression.first
  end

  def penalty
    @user_game = UserGame.find(params[:user_game_id])
    @user_game.penalty += 1
    @user_game.save
    @enigma = Enigma.find(params[:enigma_id])

    respond_to do |format|
      format.json
    end
  end

  def update

    @user_game = UserGame.find(params[:id])
    @user_game.update(user_game_params)
    @user_game.save
    redirect_to notes_path
  end


  def victory
    @user_game = UserGame.find(params[:id])

    if params["code"] == "3492179918"

      @user_game.succeeded_at = Time.now
      @user_game.save
      redirect_to ending_adventure_show_path
    else
      @user_game.penalty += 1
      @user_game.save
      redirect_to enigma_path(Enigma.last)
    end


  end

  private

  def user_game_params
    params.require(:user_game).permit(:note)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CityBreak</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>

    <div class="big_content">
     <%= yield %>
    </div>

  </body>
</html>

app/views/pages/components.html.erb
<div class="container">
<h1>Voici tous les composants</h1>


<h2>LES BOUTONS</h2>

<a class = "btn_green_jouer" href="#">Jouer</a>
<a class = "btn_green_suivant" href="#">Suivant</a>





<h2>VOICI LES CARDS </h2>

<div class="cards">


<div class= "card_enigme">
<h3>Un volatile vous surveille</h3>
  <p>bla bla bla bla et bla bla bla</p>
</div>





<div class="card_jeu_photo">
 <div class ="infos">
  <h3>Validez votre choix</h3>
  </div>
    <div class = "photos">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTefbeKbMMCLHVBPLtx3OKeYz6168z1jymBn9Pg8SYtmTUzvgvP" alt="photo1">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTefbeKbMMCLHVBPLtx3OKeYz6168z1jymBn9Pg8SYtmTUzvgvP" alt="photo1">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTefbeKbMMCLHVBPLtx3OKeYz6168z1jymBn9Pg8SYtmTUzvgvP" alt="photo1">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTefbeKbMMCLHVBPLtx3OKeYz6168z1jymBn9Pg8SYtmTUzvgvP" alt="photo1">
    </div>
</div>




</div>






<h2>NAVBAR PENDANT UNE PARTIE </h2>

<div class="navbar_game">
  <a class="active" href="#"><i class="fa fa-fw fa-home"></i> Home</a>
  <a href="#"><i class="fa fa-fw fa-user"></i> Profil</a>
  <a href="#"><i class="fa fa-fw fa-circle-info"></i> Indices</a>
  <a href="#"><i class="fa fa-fw fa-bomb"></i> Bombe</a>

</div>






<h2>NAVBAR DE LA HOME</h2>

<div class="">
  <a href=""><i class="fa fa-fw fa-user"></i></a>
  <a href="#"><i class="fa fa-fw fa-list"></i> Règles</a>
  <a href="#"><i class="fa fa-fw fa-gear"></i> Réglages</a>


</div>





</div>



 <%# body {
      font-family: Arial, sans-serif;
    }
    .container {
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
    }
    textarea {
      width: 100%;
      height: 300px;
      margin-bottom: 10px;
    }
    button {
      padding: 10px 20px;
      background-color: #4CAF50;
      color: white;
      border: none;
      cursor: pointer; %>

app/views/pages/defeat.html.erb
  <div class="card_enigme">
    <h1>LILLE EST DETRUITE </h1>
    <p> vous avez failli à votre mission. </p>

      <%= link_to home_path do %> Retour au menu
  <% end %>

  </div>

app/views/pages/ending_adventure_show.html.erb
<div class="content_cards">
  <div class="card_enigme">
    <h1>BRAVO !! </h1>
      <p> L'horloge tiquait, la menace grandissait, mais vous n'avez pas fléchi.Vous avez relevé le défi du Pélican, déchiffré ses énigmes tordues et contrecarré son plan malveillant qui menaçait notre cité bien-aimée.</p>
      <p> Vous avez mérité d'aller boire une bonne bière et deguster l'une de nos délicieuses spécialitée culinaire.</p>
      <p> Avec une gratitude infinie, nous vous disons : Merci.
      <p> Vous avez sauvé Lille. </p>
      <div class="poster">
        <p> <img src="https://imagizer.imageshack.com/img923/1715/uRZKnj.jpg" alt=""></p>
        <p> <%#= link_to "Voir le score final", final_score_path %> </p>
        <%= link_to "Retour au menu", home_path, class: "continuez" %>
      </div>
  </div>
</div>

app/views/pages/final_score.html.erb
<div class="content_final_score">
  <div class="score">
    <h2>Votre score :</h2>

  </div>

  <div class="classement">
    <h3>Classement :</h3>
    <ol>
      <li>Joueur 1</li>
      <li>Joueur 2</li>
      <li>Joueur 3</li>
    </ol>
  </div>

  <div class="button-group">
    <%#= link_to "Share", share_path, class: "btn_green_suivant" %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="content_home">
  <div class="toplane">
    <img src="http://imagizer.imageshack.com/v2/976x487q50/r/922/dGtfvR.png" alt="">

      <div class="titre">

        <h2>Selectionnez un scénario !</h2>

      </div>
  </div>
  <div class="all_games">
    <div class="Tuto">
      <h2> <%= link_to "Tutoriel", tutoriel_path%> </h2>
    </div>
        <div class= "Alerte">
          <% @games.each do |game| %>
           <h2><%= link_to "Alerte à Lille", game_path(game), class:"btn_alerte" %></h2>
          <%end %>
    </div>
    <div class="Apo">
      <h2>Apoca<font color="#CE0707"> LILLE</font>pse</h2>
    </div>

  </div>
    <div class="centered-button">
  <%= button_to "Déconnexion", destroy_user_session_path, method: :delete, class: "custom-button" %>
</div>



  <div class="navbar_home">

    <div class="regles">
    <%= link_to rules_path do %>
      <i class="fa fa-fw fa-list"></i>
    <% end %>
    </div>
    <div class="profil">
    <%= link_to profil_path do %>
      <i class="fa fa-fw fa-user"></i>
    <% end %>
    </div>
    <div class="reglages">
    <%= link_to reglages_path do %>
      <i class="fa fa-fw fa-gear"></i>
    <% end %>
    </div>
  </div>
</div>

app/views/pages/notes.html.erb
 <div class="content_bloc">
 <div class="bloc_infos">

 <h1>Bloc-notes</h1>
  <%# <textarea id="note" placeholder="Saisissez votre note ici"></textarea>
  <button onclick="saveNote()">Enregistrer</button> %>


  <%= simple_form_for @user_game do |f|%>
    <%= f.input_field :note, id: "note", placeholder: "Saisissez votre note ici", value: @user_game.note, label: false%>
    <%= f.submit class: "d-none" %>
  <% end %>
<div class="content-btn">
  <button class="enregistrer" onclick="saveNote()">Enregistrer</button>
  </div>
  </div>
  <div class="navbar_home">
<div class='profil'>
  <%= link_to :back do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>
  </div>
</div>
</div>

  </div>



</div>

<script>
  // Fonction pour enregistrer la note dans le stockage local
  function saveNote() {
    var note = document.getElementById('note').value;
    localStorage.setItem('userNote', note);
    alert('La note a été enregistrée avec succès !');
  }

  // Restaurer la note précédemment enregistrée lors du chargement de la page
  window.onload = function() {
    var savedNote = localStorage.getItem('userNote');
    if (savedNote) {
      document.getElementById('note').value = savedNote;
    }
  };
</script>

app/views/pages/profil.html.erb
<div class="full_rules">

<div class="content_rules">
    <div class= "rules_infos">
      <h2>Mon profil</h2>
      <p>Nous travaillons sur votre profil. Revenez bientôt pour le découvrir !</p>
    </div>
  </div>



<div class="navbar_home">
<div class='profil'>
  <%= link_to home_path do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>
  </div>
</div>
</div>

app/views/pages/reglages.html.erb
<div class="full_rules">

<div class="content_rules">
    <div class= "rules_infos">
      <h2>Réglages</h2>
      <p>Nous travaillons sur les réglages. Revenez bientôt pour le découvrir !</p>
    </div>
  </div>



<div class="navbar_home">
<div class='profil'>
  <%= link_to home_path do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>
  </div>
</div>
</div>

app/views/pages/rules.html.erb
<div class="full_rules">

<div class="content_rules">
    <div class= "rules_infos">
      <h2>L'Énigme du Pélican :
      <br>L'Escape Game Interactif de Lille</h2>
      <p>Objectif du Jeu :

Votre mission, si vous l'acceptez, est de sauver la ville de Lille d'un désastre imminent. Un criminel connu sous le nom du "Pélican" a planifié de détruire la ville avec une bombe fabriquée à partir d'Orge et de Malt. Vous devez résoudre une série d'énigmes et déchiffrer les indices laissés par le Pélican pour désamorcer la bombe et sauver la ville. Vous avez seulement 60 minutes pour réaliser cette mission.

Règles du Jeu :

Type de jeu : Il s'agit d'un jeu d'évasion interactif (Escape Game) dans lequel vous êtes plongé au cœur de Lille. Le jeu se déroule en temps réel, avec des indices cachés et des énigmes à résoudre dans différents lieux de la ville. Vous devrez explorer, observer et déduire pour arriver à votre objectif.

Bloc-note de joueur : Pour vous aider à suivre les indices, vous avez la possibilité de stocker les chiffres que vous collectez dans un bloc-note virtuel. Utilisez-le pour garder une trace des chiffres importants tout au long de votre enquête.

Temps limite : Vous disposez de 60 minutes pour déjouer le plan du Pélican et sauver Lille. Ce compte à rebours commence dès que vous commencez votre mission.

Réponses incorrectes et code de la bombe : Chaque fois que vous donnez une réponse incorrecte à une énigme, ou que vous entrez un code incorrect pour la bombe, 1 minute est soustraite du temps total pour sauver la ville. Il est donc crucial de bien réfléchir avant de répondre ou de tenter de désamorcer la bombe.

Indices et énigmes : Le Pélican a semé la ville d'indices et d'énigmes qui, une fois résolus, vous rapprocheront de la bombe. Chaque fois que vous trouvez et ouvrez un nouvel indice, 1 minute est soustraite du temps total pour sauver la ville.

Fin du jeu : Le jeu se termine lorsque vous avez désamorcé la bombe et sauvé la ville, ou lorsque le temps est écoulé. Dans le dernier cas, malheureusement, le Pélican a réussi son plan maléfique et Lille est perdue.

Soyez vigilant, utilisez votre esprit de déduction et travaillez rapidement. Chaque minute compte dans votre mission pour sauver Lille du Pélican. Bonne chance !</p>
    </div>
  </div>



<div class="navbar_home">
<div class='profil'>
  <%= link_to home_path do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>
  </div>
</div>
</div>

app/views/pages/tutoriel.html.erb
<div class="full_rules">

<div class="content_rules">
    <div class= "rules_infos">
      <h2>Tutoriel</h2>
      <p>Nous travaillons sur ce tutoriel. Revenez bientôt pour le découvrir !</p>
    </div>
  </div>



<div class="navbar_home">
<div class='profil'>
  <%= link_to home_path do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>
  </div>
</div>
</div>

app/views/shared/_timer.html.erb
  <%# TIMER %>
<div class="timer-color-text" data-penalty-target="timer">
  <% seconds_until_target_time = @user_game.end_of_game_time.to_i - (60 * @user_game.penalty) - Time.now.to_i%>


    <%= content_tag(:h4, "",class: "toto", data: {
      controller: "countdown",
      countdown_target: "countdown",
      seconds_until_end_value: seconds_until_target_time
    }) %>
</div>

  <%# TIMER %>