config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get '/home', to: "pages#home"
  get '/components', to: "pages#components"  #a retirer
  get '/rules', to: "pages#rules"
  get '/tutoriel', to: "pages#tutoriel"
  get '/reglages', to: "pages#reglages"
  get '/profil', to: "pages#profil"
  get 'pages/ending_adventure_show', to: 'pages#ending_adventure_show', as: 'ending_adventure_show'
  get 'pages/defeat', to: 'pages#defeat', as: 'defeat'

  get '/final_score', to: 'pages#final_score', as: 'final_score'
  get 'pages/notes', to: 'pages#notes', as: 'notes'

  get '/hint', to: "pages#hint"
  get '/user_games/:user_game_id/enigma/:enigma_id', to: "user_games#penalty", as: "penalty"

  post "/user_games/:id/victory", to: "user_games#victory", as: 'victory'

  resources :games do
    # resources :user_games, only: [:create]
    # resources :enigmas, only: [:show]
    resources :user_games, only: [:create]

  end

  resources :user_games, only: [:show, :update]
  resources :enigmas, only: [:show]

  resources :enigmas do
    get 'false_answer_popup', on: :member
      get 'hint_popup', on: :member
      get '/enigmas/bomb', to: 'enigmas#bomb', as: 'bomb'

  end





resources :point_of_interests, only:[:show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :enigma
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :users
end

app/models/enigma.rb
class Enigma < ApplicationRecord
  belongs_to :point_of_interest, optional: true
  has_many :answers
  has_one :hint
  belongs_to :game, class_name: 'Game'
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :user_games
  has_many :enigmas
end

app/models/hint.rb
class Hint < ApplicationRecord
  belongs_to :enigma
  has_many :user_games_hints
end

app/models/point_of_interest.rb
class PointOfInterest < ApplicationRecord
  has_many :enigmas

  def enigma
    enigmas.first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_games, dependent: :destroy
  # belongs_to :badge
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_game.rb
class UserGame < ApplicationRecord
  belongs_to :user
  belongs_to :game
  has_many :user_games_hints
end

app/models/user_game_hint.rb
class UserGameHint < ApplicationRecord
  belongs_to :hints
  belongs_to :user_games
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :set_enigma, only: [:index, :new, :create]

  def index
    @answers = @enigma.answers
  end

  def show
  end

  def new
    @answer = @enigma.answers.build
  end

  def create
    @answer = @enigma.answers.build(answer_params)

    if @answer.save
      redirect_to @answer, notice: 'Answer was successfully created.'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer, notice: 'Answer was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to answers_url, notice: 'Answer was successfully destroyed.'
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_enigma
    @enigma = Enigma.find(params[:enigma_id])
  end

  def answer_params
    params.require(:answer).permit(:enigma_id, :is_good_answer, :content, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(params[:id])
    @badge = current_user
  end
end

app/controllers/enigmas_controller.rb
class EnigmasController < ApplicationController
  before_action :set_enigma, only: [:show, :update, :destroy]

  def index
    @enigmas = Enigma.all
  end

  def show
    @answers = @enigma.answers
    @last_enigma = Enigma.last
    @user_game = UserGame.where(user: current_user).last

  end

  def new
    @enigma = Enigma.new
  end


  def create
    @enigma = Enigma.new(enigma_params)

    if @enigma.save
      redirect_to @enigma, notice: 'Enigma was successfully created.'
    else
      render :new
    end
  end

  def update
    if @enigma.update(enigma_params)
      redirect_to @enigma, notice: 'Enigma was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @enigma.destroy
    redirect_to enigmas_url, notice: 'Enigma was successfully destroyed.'
  end

  private

  #PAS CERTAIN, Permet de choisir l'énigme et ses POI, Hints associés en fonction.
  def set_enigma
    @enigma = Enigma.find(params[:id])
  end

  def enigma_params
    params.require(:enigma).permit(:title, :description, :image)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  skip_before_action :authenticate_user!, only: :show
  def show
    @game = Game.find(params[:id])
  end


end

app/controllers/hints_controller.rb
class HintsController < ApplicationController
  before_action :set_point_of_interest, only: [:show]

  def index
    @hints = Hint.all
  end

  def show
  end

  private

  def set_hint
    @hint = Hint.find(params[:id])
  end

  def hint_params
    params.require(:hint).permit(:content, :enigma_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 # skip_before_action :authenticate_user!, only: :home

  def home
    @games = Game.all
  end

  def components
  end

  def ending_adventure_show
  end

  def final_score
  end

  def notes

    @user_game = UserGame.where(user: current_user).last
  end

  # def bombe
  #   @user_game = UserGame.where(user: current_user).last
  # end

  def defeat
  end

  # def bombe_answer
  #   if params["code"] == "3492179918"
  #     redirect_to ending_adventure_show_path
  #   end
  # end

end

app/controllers/point_of_interests_controller.rb
class PointOfInterestsController < ApplicationController
  before_action :set_point_of_interest, only: [:show]
  def index
    @points_of_interest = PointOfInterest.all
  end

  def show
    @user_game = UserGame.where(user: current_user).last
  end


  private

  def set_point_of_interest
    @point_of_interest = PointOfInterest.find(params[:id])
  end

  def point_of_interest_params
    params.require(:point_of_interest).permit(:anecdote, :poster_url)
  end
end

app/controllers/user_game_hints_controller.rb
class UserGameHintsController < ApplicationController
end

app/controllers/user_games_controller.rb
class UserGamesController < ApplicationController

  def index
    @user_game = current_user.users
  end


  def create
    @user_game = UserGame.new
    @user_game.user = current_user
    @user_game.game = Game.find(params[:game_id])
    @user_game.end_of_game_time = Time.now + @user_game.game.max_duration_in_sec
    @user_game.save
    redirect_to enigma_path(@user_game.game.enigmas.first)
  end

  def show
    @user_game = UserGame.find(params[:id])
    @enigmas = Enigma.where(game_id: @user_game.game.id)
  end

  def progression
    @progression = Enigma.all
    @start = @progression.first
  end

  def penalty
    @user_game = UserGame.find(params[:user_game_id])
    @user_game.penalty += 1
    @user_game.save
    @enigma = Enigma.find(params[:enigma_id])

    respond_to do |format|
      format.json
    end
  end

  def update

    @user_game = UserGame.find(params[:id])
    @user_game.update(user_game_params)
    @user_game.save
    redirect_to notes_path
  end


  def victory
    @user_game = UserGame.find(params[:id])

    if params["code"] == "3492179918"

      @user_game.succeeded_at = Time.now
      @user_game.save
      redirect_to ending_adventure_show_path
    else
      @user_game.penalty += 1
      @user_game.save
      redirect_to enigma_path(Enigma.last)
    end


  end

  private

  def user_game_params
    params.require(:user_game).permit(:note)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/enigmas/_bombe.html.erb
<div class="background_bomb">
  <div class="content_bombe">
  <%# <img src="https://imagizer.imageshack.com/img924/7499/V02y6Y.png" alt=""> %>
    <div class= "bombe_infos">


      <h2><%= @enigma.title  %></h2>
        <div class="validate">
          <%= form_with url: victory_path(@user_game), method: :post do %>
            <%= text_field_tag :code,
                params[:code],
                placeholder: "rentrez le code"%>
                    <%= submit_tag "desactiver" %>
                    <% end %>
        </div>
    </div>
    <div class="code-input">
  </div>

</div>
</div>




<%# <div class="navbar_home">
  <a href="" onclick="history.back()">
    <i class="fa-solid fa-arrow-left"></i> Back
  </a>
</div> %>

app/views/enigmas/_figuresenigma.html.erb
<div class="card_enigme">
      <%# <br>
      <br>
      <br>
      <br> %>

  <h1><%= @enigma.title %></h1>
  __________________________
  <p><%= @enigma.description.html_safe %></p>


 <% if @enigma.point_of_interest %>
      <%= link_to "Continuer", point_of_interest_path(@enigma.point_of_interest), class:"continuez" %>

    <% else %>
      <%= link_to "Continuer", enigma_path(Enigma.find_by_order_in_the_game(@enigma.order_in_the_game + 1)), class:"continuez" %>
      <%#= link_to "Voir le score final", final_score_path %>

      <% end %>
      <%# <br>
      <br>
      <br>
      <br> %>

</div>

app/views/enigmas/_minigame.html.erb
<div class="card_enigme" data-controller="puzzle">

  <h1><%= @enigma.title %></h1>
  __________________________
  <p> <%= @enigma.description.html_safe %> </p>

  <div class="puzzle" data-puzzle-target="puzzle">
    <div class="tile" data-puzzle-target="tile" data-order="6" style='background-image: url(<%=asset_url("6.jpg")%>);'></div>
    <div class="tile" data-puzzle-target="tile" data-order="1" style='background-image: url(<%=asset_url("1.jpg")%>);'></div>
    <div class="tile" data-puzzle-target="tile" data-order="4" style='background-image: url(<%=asset_url("4.jpg")%>);'></div>
    <div class="tile" data-puzzle-target="tile" data-order="2" style='background-image: url(<%=asset_url("2.jpg")%>);'></div>
    <div class="tile" data-puzzle-target="tile" data-order="7" style='background-image: url(<%=asset_url("7.jpg")%>);'></div>
    <div class="tile" data-puzzle-target="tile" data-order="3" style='background-image: url(<%=asset_url("3.jpg")%>);'></div>
    <div class="tile" data-puzzle-target="tile" data-order="5" style='background-image: url(<%=asset_url("5.jpg")%>);'></div>
    <div class="tile" data-puzzle-target="tile" data-order="8" style='background-image: url(<%=asset_url("8.jpg")%>);'></div>
  </div>
  <% if @enigma.point_of_interest %>
    <%= link_to "Continuer", point_of_interest_path(@enigma.point_of_interest), class: "continuez", data:{action: "click->puzzle#validate"}%>

  <% else %>
      <%= link_to "Continuer", enigma_path(Enigma.find_by_order_in_the_game(@enigma.order_in_the_game + 1)), class:"continuez" %>
  <% end %>

<%# NE PAS SUPPRIMER CE LIEN %>
  <%= link_to "penalty", penalty_path(@user_game, @enigma), class: "false-answer-button d-none", remote: true, data:{action: "click->penalty#send", puzzle_target:"penalty"}  %>


</div>

app/views/enigmas/_photos_QCM.html.erb
<div class="card_enigme">
  <h1><%= @enigma.title %></h1>
  __________________________
  <p><%= @enigma.description.html_safe %></p>

  __________________________

  <%# <div class="card_jeu_photo"> %>
<h3>Valide ton choix</h3>
  <div class="infos">

    <div class="photo_answer">
      <% @enigma.answers.shuffle.each do |answer| %>
        <% if answer.is_good_answer %>
          <% if @enigma.point_of_interest %>
            <%= link_to point_of_interest_path(@enigma.point_of_interest), class: "answer-link" do %>
              <div class="photos" style="background-image: url('<%= answer.poster_url %>');">
                <%# <%= answer.content %>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to penalty_path(@user_game, @enigma), class: "false-answer-button", remote: true, data:{action: "click->penalty#send"} do %>
            <div class="photos" style="background-image: url('<%= answer.poster_url %>');">
              <%# <%= answer.content %>
            </div>
            <% end %>
        <% end %>

      <%# <% else %>

        <%# <%= link_to "False Answer", penalty_path(@user_game, @enigma), class: "false-answer-button", remote: true, data:{turbo_method: "patch"} %>

      <% end %>
    </div>
  </div>

</div>
  <%# <%= link_to enigma_path(Enigma.find_by_order_in_the_game(@enigma.order_in_the_game + 1))  %>

app/views/enigmas/_resolution_game.html.erb
<div class="card_enigme">

  <h1><%= @enigma.title %></h1>
  __________________________
  <p><%= @enigma.description.html_safe %></p>

   _________________________

  <%= link_to "DESACTIVER LA BOMBE !!", enigma_path(Enigma.find_by_order_in_the_game(@enigma.order_in_the_game + 1)), class:"desactiver" %>

</div>

app/views/enigmas/false_answers_popup.html.erb
<div class="popup-false-answer">
  <h1>MAUVAISE REPONSE !</h1>
  <p>Ta réponse est incorrecte, la ville sautera une minute plus tôt, cliques sur la croix pour pouvoir choisir une autre réponse.</p>
</div>

app/views/enigmas/hint_popup.html.erb
<div class="popup-hint">
  <h1>Hint</h1>
  <p><%= @hint.content %></p>
    <p>Cet indice te fait perdre une minute pour sauver la ville</p>

</div>

app/views/enigmas/show.html.erb
<div class="card_enigme-container">
  <div class="content_cards" data-controller="penalty">
    <%= render "shared/timer"  %>
      <% case @enigma.enigma_type %>
        <% when "figuresenigma" %>
          <%= render 'figuresenigma' %>
        <% when "photos_QCM" %>
          <%= render 'photos_QCM' %>
        <% when "minigame" %>
          <%= render 'minigame' %>
        <% when "bombe" %>
          <%= render 'bombe' %>
        <% when "resolution_game" %>
          <%= render 'resolution_game' %>
      <% end %>
    <div class="navbar_inside">
      <div class="home">
        <%= link_to home_path do %>
        <a class="home" href="#"><i class="fa fa-fw fa-home"></i></a>
         <% end %>
      </div>
        <%# <a href="#"><i class="fa fa-fw fa-user"></i> Profil</a> %>
        <%# <a href="#"><i class="fa fa-fw fa-circle-info" ></i> Indices</a> %>
        <div class="indices" >
          <a onclick="window.dialog.showModal();"><i class="fa fa-fw fa-circle-info"></i></a>
        </div>
        <dialog id="dialog">
          <div class="popup-text">
            <h2>Indice de l'enigme</h2>
              <%# <p>A CSS-only modal based on the <a href="https://developer.mozilla.org/es/docs/Web/CSS/::backdrop" target="_blank">::backdrop</a> pseudo-class. Hope you find it helpful.</p> %>
                <% if @enigma.hint.nil? %>
                  <p> Aucun indice pour cette enigme </p>
                <% else %>
                  <p><%=@enigma.hint.content %></p>
                <% end %>
            <button onclick="window.dialog.close();" aria-label="close" class="x">❌</button>
          </div>
        </dialog>
      <div class="bombe">

        <%= link_to notes_path do %>
        <i class="fa-regular fa-pen-to-square"></i>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<div class="big-content">
  <div class="principal-synop">
    <div class="synopsis-font">
        <div class= "Alerte-synop">
          <h2>Alerte à Lille</h2>
        </div>
        <div class="synopsis">
          <p><%= @game.synopsis.html_safe %></p>
        </div>
    </div>
  </div>
  <div class="navbar_game">
    <div class="play" data-controller="start-game">
      <a href=""><i class="fa fa-fw fa-play" data-action= "click->start-game#start"></i></a>
        <%= link_to game_user_games_path(@game),class: "d-none", data: { turbo_method: "POST", start_game_target: "start"} do %>
          <i class="fa fa-fw fa-play"></i>
        <% end %>
    </div>
  </div>
</div>

app/views/hints/show.html.erb
<div class="content_rules">
    <div class= "rules_infos">
      <h2>A fond les Indices</h2>
      <p> la somme des ciffrs est égal a la femme d'un élan</p>
    </div>
  </div>



<div class="navbar_home">
  <a href="" onclick="history.back()">
    <i class="fa-solid fa-arrow-left"></i> Back
  </a>
</div>

app/views/point_of_interests/show.html.erb
<div class="card_enigme-container">

<div class= "content_cards">
<%= render "shared/timer"  %>
  <div class= "card_enigme">
<h1>BRAVO !</h1>
_________________________
<h2><%=@point_of_interest.titre %></h2>


<p><%= @point_of_interest.anecdote.html_safe %></p>

<div class="poster">
 <img src="<%=@point_of_interest.poster_url %>" alt="">

 _________________________
</div>
<br>
<h2>Prochaine étape</h2>

<p><%= @point_of_interest.indication_next_step.html_safe %></p>
<%= link_to "Continuer",enigma_path(Enigma.find_by_order_in_the_game(@point_of_interest.enigma.order_in_the_game + 1)), class:"continuez" %>

</div>




</div>

</div>

app/views/user_games/show.html.erb
<h1>c'est parti !</h1>

<p>Vous jouez à :</p>
<%= @user_game.game.title %>
<p> <%= %> </p>
<p>Fin du jeu : <%= @user_game.end_of_game_time %></p>
<p></p>